### ISSUE TITLE
Format of cmdline.d/*.conf should be specified

### ISSUE THREAD

**Issue by bwarden** [clearlinux/clr-boot-manager#103]
https://github.com/clearlinux/clr-boot-manager/blob/50cc4ea5f967dcf7a51a4c089d4f7bb4cfae9160/man/clr-boot-manager.1.in#L101

We should specify that the contents of any cmdline.d/*.conf must be simple text to be appended directly to the kernel command line.

We should also mention that contents from /usr/lib/kernel/cmdline* and /usr/lib/kernel/cmdline.d/*.conf are used in generation of the command line.

**Comment by bryteise** [comment]
@bwarden Mind taking a look at #127 to see if this is what you were hoping to see?

**Comment by dorileo** [comment]
@bwarden  it seems this issue was fixed with #127. Please feel free to reopen it if think we're still missing something.

Thanks.
