### ISSUE TITLE
EFI data installs to non-EFI partition mounted at /boot

### ISSUE THREAD

**Issue by bryteise** [clearlinux/clr-boot-manager#113]
If the system being updated has /boot mounted as a non EFI partition and clr-boot-manager is configured for an EFI bootloader, /boot will still be populated with EFI content.

Likely need to try and find an EFI partition or just not install content. @ikeydoherty Any thoughts on this?

**Comment by dorileo** [comment]
@bryteise I'm not sure this is still true. I can double check later.

**Comment by dorileo** [comment]
yeah! just checked, with LegacyBIOS mode we no longer install efi content.
