### ISSUE TITLE
Sets Clear Linux as the only bootable OS

### ISSUE THREAD

**Issue by bwarden** [clearlinux/clr-boot-manager#122]
Copied from https://github.com/clearlinux/distribution/issues/142

> I do have several distributions in my system, and all boot through EFI, now ClearLinux thinks, it is the only OS to be in the system and fiddle with the boot section.
> 
> Do not write or mess with the boot section...at least ask the end user, that you want to update it or want to do it in a proper way??
> 
> Sound naive?? Sound stupid?? can't help. That is what bugs me. I tried to bypass it and it is still bugging.
> 
> I am sure, I am certainly missing some arcane details to get on.
>

**Comment by dorileo** [comment]
I can say this is not true anymore, I'm closing this one, please feel free to reopen it if necessary. Thanks.
