### ISSUE TITLE
cannot see or set kernel using LegacyBIOS

### ISSUE THREAD

**Issue by jascott1** [clearlinux/clr-boot-manager#131]
Hi,

I have been using LegacyBIOS with the kvm-kernel and noticed that clr-boot-manager 
* does not indicate which listed kernel is selected (missing asterisk)
* throws an error when I attempt to update

Perhaps this is fixed in #129 but wanted to file just in case. I assume legacyBIOS is the problem because clr-boot-manager works for me in instances where its not enabled.

**Comment by dorileo** [comment]
hi @jascott1 I just tested with a similar environment, kvm on legacy bios mode, the update command works just fine. the `clr-boot-manager list-kernels` indeed doesn't mark the default kernel. I've just created a new issue (#211) to track this. I'm closing this one, please feel free to reopen if necessary. Thanks.
