### ISSUE TITLE
Support user configured freestanding initrd files

### ISSUE THREAD

**Issue by bryteise** [clearlinux/clr-boot-manager#187]
Currently Clear Linux supports an INITRD_DIRECTORY for the vendor but not for the user. It would be beneficial to enable users to add their own freestanding initrd files and override the vendor provided ones. To do so, the following would be needed:
* Add an additional parameter to meson.build for a user initrd directory
* Add a BootManager field to contain the user configured directory
* When adding initrd files from the freestanding directories, ensure that the user configured initrds have priority over the vendor initrds (enable masking if the same name is linked to /dev/null as well)

**Comment by dorileo** [comment]
Merged recently, will land in clr soon.

Thanks.
