### ISSUE TITLE
Add an option for clr-boot-manager to not change the boot order when running `update`

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clr-boot-manager#188]
Currently, `clr-boot-manager update` modifies the boot order to make Clear the first one. 
This can be a problem for a multi-boot system where another bootloader is set as the default.  
It would be good to have an option for `clr-boot-manager update` to not modify the boot order.

**Comment by dorileo** [comment]
The plan is to introduce a configuration option to avoid changing the boot order efi vars, in these situations the user is manually configuring their multi-boot systems and we want c-b-m to no mess with users configuration.

**Comment by dorileo** [comment]
Changes were merged, will land in clr soon.

Thanks.
