### ISSUE TITLE
Latest release is wrongly labeled as 3.2.0 (should be 3.2.1)

### ISSUE THREAD

**Issue by Jacalz** [clearlinux/clr-boot-manager#197]
The new release of version 3.2.1 yesterday is named exactly as the release before it. Please fix that, so it says 3.2.1 🙂 
https://github.com/clearlinux/clr-boot-manager/releases

**Comment by dorileo** [comment]
Fixed. Thanks for pointing out.

**Comment by Jacalz** [comment]
You’re welcome. Happy to be of service 🙂
