### ISSUE TITLE
cbm update fails to perform; reinstall does not work

### ISSUE THREAD

**Issue by felixg3** [clearlinux/clr-boot-manager#201]
Hello,

unfortunately I have created issues with the boot partition. During my attempts to repair /boot/efi, I think I wiped the partition. However here are my error logs that I have recorded. Unfortunately I rely on keeping this system running till I found a solution (silly, I know. Good this is my dev machine and not a production system).

`$ sudo blkid`

/dev/nvme0n1p1: LABEL_FATBOOT="boot" LABEL="boot" UUID="0CB0-682D" TYPE="vfat" PARTLABEL="EFI" PARTUUID="830d1e5b-0989-431d-b2b4-91ae484e7df5"
/dev/nvme0n1p2: LABEL="swap" UUID="aa37385f-61f9-47bd-931a-39c0570ed6a0" TYPE="swap" PARTLABEL="linux-swap" PARTUUID="b8969617-aadb-43ae-bf18-013c2cf112bc"
/dev/nvme0n1p3: UUID="f0025b51-de28-42eb-a8a1-1235b4d0851b" TYPE="crypto_LUKS" PARTLABEL="/" PARTUUID="3b84c3db-aa6d-402d-b0f7-134e8b772d16"
/dev/mapper/luks-f0025b51-de28-42eb-a8a1-1235b4d0851b: LABEL="root" UUID="0ebbc71d-a3e4-4b66-b11f-be9b366ba525" TYPE="ext4"

`$ sudo blkid -p /dev/nvme0n1p1`

/dev/nvme0n1p1: LABEL_FATBOOT="boot" LABEL="boot" UUID="0CB0-682D" VERSION="FAT32" TYPE="vfat" USAGE="filesystem" PART_ENTRY_SCHEME="gpt" PART_ENTRY_NAME="EFI" PART_ENTRY_UUID="830d1e5b-0989-431d-b2b4-91ae484e7df5" PART_ENTRY_TYPE="c12a7328-f81f-11d2-ba4b-00a0c93ec93b" PART_ENTRY_NUMBER="1" PART_ENTRY_OFFSET="2048" PART_ENTRY_SIZE="290816" PART_ENTRY_DISK="259:0"

`$ sudo env CBM_DEBUG=1 clr-boot-manager update`

[DEBUG] cbm (../src/cli/cli.c:L142): No such file: //etc/kernel/update_efi_vars
[INFO] cbm (../src/bootman/bootman.c:L729): Current running kernel: 5.4.4-879.native
[INFO] cbm (../src/bootman/sysconfig.c:L179): Discovered UEFI ESP: /dev/disk/by-partuuid/830d1e5b-0989-431d-b2b4-91ae484e7df5
[INFO] cbm (../src/bootman/sysconfig.c:L256): Fully resolved boot device: /dev/nvme0n1p1
[DEBUG] cbm (../src/lib/probe.c:L261): Root device exists on device-mapper configuration
[DEBUG] cbm (../src/bootman/bootman.c:L135): shim-systemd caps: 0x26, wanted: 0x26
[DEBUG] cbm (../src/bootman/bootman.c:L150): UEFI boot now selected (shim-systemd)
[INFO] cbm (../src/bootman/bootman.c:L749): path ///etc/kernel/initrd.d does not exist
[DEBUG] cbm (../src/bootman/bootman.c:L769): Non regular file: ///usr/lib/initrd.d/.., skipping.
[DEBUG] cbm (../src/bootman/bootman.c:L769): Non regular file: ///usr/lib/initrd.d/., skipping.
[INFO] cbm (../src/bootman/bootman.c:L454): Checking for mounted boot dir
[DEBUG] cbm (../src/lib/files.c:L577): Directory /boot is not empty, found: efi
[INFO] cbm (../src/bootman/bootman.c:L462): boot_dir is already mounted: /boot
[DEBUG] cbm (../src/bootman/update.c:L164): Now beginning update_native
[DEBUG] cbm (../src/bootman/update.c:L173): update_native: 2 available kernels
[DEBUG] cbm (../src/bootman/update.c:L191): update_native: Running kernel is (native) ///usr/lib/kernel/org.clearlinux.native.5.4.4-879
[ERROR] cbm (../src/lib/bootvar.c:L320): blkid_probe_get_partitions() error
[ERROR] cbm (../src/lib/bootvar.c:L320): blkid_probe_get_partitions() error
[ERROR] cbm (../src/bootloaders/shim-systemd.c:L284): Cannot create EFI variable (boot entry)
[ERROR] cbm (../src/bootloaders/shim-systemd.c:L285): Please manually update your bios to add a boot entry for Clear Linux
[SUCCESS] cbm (../src/bootman/update.c:L205): update_native: Bootloader updated
[SUCCESS] cbm (../src/bootman/update.c:L220): update_native: Repaired running kernel ///usr/lib/kernel/org.clearlinux.native.5.4.4-879
[DEBUG] cbm (../src/bootman/update.c:L230): update_native: Checking kernels for type native
[INFO] cbm (../src/bootman/update.c:L243): update_native: Default kernel for type native is ///usr/lib/kernel/org.clearlinux.native.5.4.5-882
[SUCCESS] cbm (../src/bootman/update.c:L255): update_native: Installed tip for native: ///usr/lib/kernel/org.clearlinux.native.5.4.5-882
[SUCCESS] cbm (../src/bootman/update.c:L269): update_native: Installed last_good kernel (native) (///usr/lib/kernel/org.clearlinux.native.5.4.4-879)
[DEBUG] cbm (../src/bootman/update.c:L280): update_native: Analyzing for type native: ///usr/lib/kernel/org.clearlinux.native.5.4.5-882
[INFO] cbm (../src/bootman/update.c:L288): update_native: not-running: ///usr/lib/kernel/org.clearlinux.native.5.4.5-882
[DEBUG] cbm (../src/bootman/update.c:L291): update_native: Skipping default-native: ///usr/lib/kernel/org.clearlinux.native.5.4.5-882
[DEBUG] cbm (../src/bootman/update.c:L280): update_native: Analyzing for type native: ///usr/lib/kernel/org.clearlinux.native.5.4.4-879
[DEBUG] cbm (../src/bootman/update.c:L285): update_native: Skipping running kernel
[INFO] cbm (../src/bootman/bootman.c:L454): Checking for mounted boot dir
[DEBUG] cbm (../src/lib/files.c:L577): Directory /boot is not empty, found: efi
[INFO] cbm (../src/bootman/bootman.c:L462): boot_dir is already mounted: /boot
[SUCCESS] cbm (../src/bootman/update.c:L338): update_native: Default kernel for native is ///usr/lib/kernel/org.clearlinux.native.5.4.5-882
[DEBUG] cbm (../src/bootman/update.c:L353): No kernel removals found

After trying the solution from #https://github.com/clearlinux/clr-boot-manager/issues/179 
I wiped my whole /boot/efi partition, trying to reinstall with CBM. In case sh** hits the fan, I can still restore from a full system image that is luckily only two weeks old.
Thank you a lot for your help!

**Comment by dorileo** [comment]
what's the clr-boot-manager version you running? (you can check with: clr-boot-manager version)
