### ISSUE TITLE
Kernel update wipes my custom syslinux.cfg settings

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clr-boot-manager#229]
I was running Clear 32570, manually added "TIMEOUT 50" and "PROMPT 1" to syslinux.cfg.  Then I updated Clear to 32680 and my settings were overwritten.  

Maybe we need a syslinux_custom.cfg for custom settings and CBM can concatenate it with the factory settings?

**Comment by ahkok** [comment]
does `clr-boot-manager set-timeout XXX` not work with syslinux?

**Comment by bktan8** [comment]
Not yet.  :)
